output"ip_instance_1"{
    value=aws_instance.INSTANCE_1.public_ip
}
output"ip_instance_2"{
    value=aws_instance.INSTANCE_2.public_ip
}
output"ip_instance_3"{
    value=aws_instance.INSTANCE_3.public_ip
}
